name: CI - Build and Test

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: ${{ matrix.os }}, ${{ matrix.cmake_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-11, ubuntu-20.04, ubuntu-22.04 ]
        cmake: [ 3.x ]

    runs-on: ${{ matrix.os }}

    env:
      # CMake 3.15 doesn't detect Visual Studio correctly without these.
      CXX: ${{ matrix.CXX }}
      CC: ${{ matrix.CXX }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: abdes/gha-setup-ninja@master

      - name: Setup Windows environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: ${{matrix.cmake}}

      - name: Print CMake version
        run: cmake --version

      - name: "Configure Build"
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Debug
      - name: "Build"
        run: cmake --build build --parallel
      - name: "Execute "
        run: ./crossPlatformMemoryTest
        working-directory: build
